# Generated by Django 5.0.6 on 2024-07-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addrestaurant_is_reviewed_addrestaurant_requested_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrestaurant',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='addrestaurant',
            name='requested_at',
        ),
    ]
