# Generated by Django 5.0.6 on 2024-07-25 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_addrestaurant_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrestaurant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
