# Generated by Django 5.0.6 on 2024-07-25 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_addrestaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
