# Generated by Django 5.0.6 on 2024-07-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_addrestaurant_user'),
    ]

    operations = [
    ]
