# Generated by Django 5.0.6 on 2024-07-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_default_user'),
    ]

    operations = [
    ]
