# Generated by Django 5.0.6 on 2024-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_addrestaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrestaurant',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='RequestedMenus/'),
        ),
    ]
