# Generated by Django 5.0.6 on 2024-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_menuimage_remove_addrestaurant_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrestaurant',
            name='menu_images',
        ),
        migrations.RemoveField(
            model_name='addrestaurant',
            name='created_at',
        ),
        migrations.AddField(
            model_name='addrestaurant',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='RequestedMenus/'),
        ),
        migrations.DeleteModel(
            name='MenuImage',
        ),
    ]
