# Generated by Django 5.0.6 on 2024-07-26 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_addrestaurant_menu_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrestaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
