# Generated by Django 5.0.6 on 2024-07-26 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_addrestaurant_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrestaurant',
            name='menu',
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='RequestedMenus/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='api.addrestaurant')),
            ],
        ),
    ]
