# Generated by Django 5.0.6 on 2024-07-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_addrestaurant_menu_menuimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='api.addrestaurant'),
        ),
    ]
