# Generated by Django 5.0.4 on 2024-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFind', '0003_customuser_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='map_url',
            field=models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7273.904211293504!2d85.307945566468!3d27.67357411547265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb192d79c4bca5%3A0xa7f535ecc88e78d8!2sCHi-CHi!5e0!3m2!1sen!2snp!4v1717407139008!5m2!1sen!2snp', max_length=500),
        ),
    ]
