# Generated by Django 5.0.4 on 2024-06-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFind', '0004_restaurant_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(unique=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_restaurant', to='FoodFind.restaurant')),
            ],
        ),
    ]
