# Generated by Django 5.0.4 on 2024-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFind', '0005_toprestaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(related_name='restaurants', to='FoodFind.tag'),
        ),
    ]
